### ISSUE TITLE
Local Docker container error on startup with PHP 7.0.6 image

### ISSUE THREAD

**Issue by ltouro** [appsvc/php#5]
Trying to create a new image extending **appsvc/php:7.0.6-apache-1** to add newrelic extension (like xdebug variant).

However, I'm getting this error while trying to create a new instance on my local enviroment (base image, no modifications).

I assume that Azure App Services uses the last variant available. This is correct? I mean 7.0.6-apache-1 instead php:7.0.6-apache-0 or php:7.0.6-apache.

Command:

```docker run -ti -e WEBSITE_ROLE_INSTANCE_ID=local appsvc/php:7.0.6-apache-1```

Output:
```
[....] Starting OpenBSD Secure Shell server: sshd/etc/ssh/sshd_config line 15: Deprecated option RhostsAuthentication
. ok
mkdir: cannot create directory '/var/log/apache2': File exists
touch: cannot touch '/var/log/apache2/access_local.log': No such file or directory
/bin/init_container.sh: line 9: /var/log/apache2/access_local.log: No such file or directory
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
(2)No such file or directory: AH02291: Cannot access directory '/var/log/apache2/' for main error log
AH00014: Configuration check failed
Action '-D FOREGROUND' failed.
The Apache error log may have more information.
```

**Comment by nickwalkmsft** [comment]
I believe the issue here is that the init logic is expecting /home/site/wwwroot to exist, and it doesn't in the container. In Azure, we bind-mount the site's persistent storage drive to /home, so that directory always exists, but in local usage it's not there unless you bind-mount it to something local via -v.

We are working on cleaning up our built-in images to make them easier to run locally and derive from. In the meantime, if you create a directory tree on your dev machine that contains site/wwwroot and bind-mount it to /home, it should work.

**Comment by nickwalkmsft** [comment]
Also note that the site is configured to run on port 8080 in the container. This isn't clear from the defaults, as the stock php container we inherit from exposes 80.

**Comment by ltouro** [comment]
Thank you for the quick reply! I was able to run the container, per your instructions, with the command:

```
docker run -ti -e WEBSITE_ROLE_INSTANCE_ID=local \
    -v /home/site/wwwroot \
    -v /var/log/apache2 -p 8080:8080 \
    appsvc/php:7.0.6-apache-1
```
